version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python3 manage.py runserver 0.0.0.0:8086
    volumes:
      - ./mydjangoapp:/app
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      - DEBUG=True
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
