version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8086
    volumes:
      - ./app:/opt/videoteca  # Esto está bien si deseas montar el directorio local ./app en /opt/videoteca en el contenedor
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      - DEBUG=False
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d

networks:
  mynetwork:
    driver: bridge
