version: '3.3'

services:
  db:  # Cambia el nombre del servicio de "db" a "postgres"
      image: postgres:14
      environment:
        - POSTGRES_DB=videoteca
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      # volumes: descartar
      #   - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8086
    volumes:
      - .:/app
    ports:
      - "8086:8086"
    depends_on:
      - db  
    environment:
      - DEBUG=False
    networks:
      - mynetwork

  
networks:
  mynetwork:
    driver: bridge

volumes:
  db:
    driver: local

