version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8086:8086"
    

    network_mode: "host"

# version: '3.3'
# services:
#   videoteca:
#       image: postgres:14
#       restart: always
#       environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=admin
#         - POSTGRES_DB=videoteca
#       ports:
#         - '5432:5432'
#       volumes:
#         - videoteca:/var/lib/postgresql/data
#         - "/etc/timezone:/etc/timezone:ro"
#         - "/etc/localtime:/etc/localtime:ro"
#   recursos:
#     image: postgres:14
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=admin
#       - POSTGRES_DB=recursos_humanos
#     ports:
#       - '5450:5432'
#     volumes:
#       - recursos:/var/lib/postgresql/data
#       - "/etc/timezone:/etc/timezone:ro"
#       - "/etc/localtime:/etc/localtime:ro"
# volumes:
#   videoteca:
#     driver: local
#   recursos:
#     driver: local