version: '3.3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data  

  rh:
    image: postgres:14
    environment:
      - POSTGRES_DB=recursoshumanos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/backups/recursoshumanos.sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data  

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8085
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - DEBUG=False
    restart: always  

volumes:
  postgres_data:
