version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8086:8086"
    

    network_mode: ""

  videoteca:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videoteca
    ports:
      - '5432:5432'
    volumes:
      - videoteca:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
volumes:
   videoteca:
     driver: local

