version: '3.3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d  # Monta archivos de inicialización
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5433:5432" 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8085
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - DEBUG=False

volumes:
  postgres_data:  # Define un volumen nombrado para los datos de PostgreSQL
